PetStore8/Models/RevenueViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace PetStore8.Models
{
    public class RevenueViewModel
    {
        [Key]
        public int Id { get; set; }
        [Display(Name = "From date")]
        public Nullable<System.DateTime> FromDate { get; set; }
        [Display(Name = "To date")]
        public Nullable<System.DateTime> ToDate { get; set; }
    }
}

PetStore8/Controllers/RevenueController.cs
using PetStore8.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PetStore8.Controllers
{
    [Authorize(Roles="Admin,Manager")]
    public class RevenueController : Controller
    {
        private PetStore8Entities db = new PetStore8Entities();
        // GET: Revenue
        public ActionResult Index()
        {
            return View();
        }

        // POST: Revenue
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(RevenueViewModel model)
        {
            ViewBag.OrderList = db.Orders.Where(o => o.Date >= model.FromDate && o.Date <= model.ToDate);
            return View();
        }

        public ActionResult Details(int id)
        {
            Order order = db.Orders.Find(id);
            return View(order);
        }
    }
}

PetStore8/Views/Revenue/Details.cshtml
@using PetStore8.Models
@model PetStore8.Models.Order

@{
    ViewBag.Title = "Order";
}

<h2>Order: @(Model.Id.ToString("000000"))</h2>
<br />
<b>Date: </b>@(Model.Date.ToString("MM-dd-yyyy"))
<br />
<b>Customer: </b>@(Model.Customer.AspNetUser.FirstName + " " + Model.Customer.AspNetUser.LastName)
<br />
<b>Employee: </b>@(Model.Employee.AspNetUser.FirstName + " " + Model.Employee.AspNetUser.LastName)
<br />

<table class="table">
    <tr>
        <th class="text-right">
            No.
        </th>
        <th>
            Picture
        </th>
        <th>
            Description
        </th>
        <th>
            Category
        </th>
        <th class="text-right">
            Quantity
        </th>
        <th class="text-right">
            Old Price
        </th>
        <th class="text-right">
            Discount
        </th>
        <th class="text-right">
            New Price
        </th>
        <th class="text-right">
            Amount
        </th>
    </tr>
    @{
        int i = 0;
        double totalAmount = 0;
    }
    @foreach (var item in Model.OrderDetails)
    {
        double newPrice = item.Price * (1 - item.Discount);
        double amount = item.Quantity * newPrice;
        totalAmount += amount;
        <tr>
            <td class="text-right">
                @(++i)
            </td>
            <td>
                <img src="~/products/@(item.ProductId).jpg" height="80" />
            </td>
            <td>
                @(item.Product.Description)
            </td>
            <td>
                @(item.Product.Category.Name)
            </td>
            <td class="text-right">
                @(item.Quantity)
            </td>
            <td class="text-right">
                @(item.Price.ToString("C2"))
            </td>
            <td class="text-right">
                @(item.Discount.ToString("P0"))
            </td>
            <td class="text-right">
                @(newPrice.ToString("C2"))
            </td>
            <td class="text-right">
                @(amount.ToString("C2"))
            </td>
        </tr>
    }
    <tr>
        <th colspan="8" class="text-right">Total:</th>
        <th class="text-right">@(totalAmount.ToString("C2"))</th>
        <th></th>
    </tr>
</table>

<div>
    <a href="#" onclick="history.back()">Back to List</a>
    @*@Html.ActionLink("Back to List", "Index")*@
</div>

PetStore8/Views/Revenue/Index.cshtml
@using PetStore8.Models
@model PetStore8.Models.RevenueViewModel

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

@using (Html.BeginForm("Index", "Revenue", FormMethod.Post, new { @class = "form-inline" }))
{
    @Html.AntiForgeryToken()

    <h4>RevenueViewModel</h4>
    <hr />
    <div class="form-group">
        @Html.LabelFor(model => model.FromDate, htmlAttributes: new { @class = "control-label" })
        @Html.EditorFor(model => model.FromDate, new { htmlAttributes = new { @class = "form-control", type = "date", @Value = new DateTime(DateTime.Now.Year, DateTime.Now.Month, 1).ToString("yyyy-MM-dd") } })
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.ToDate, htmlAttributes: new { @class = "control-label" })
        @Html.EditorFor(model => model.ToDate, new { htmlAttributes = new { @class = "form-control", type = "date", @Value = DateTime.Today.ToString("yyyy-MM-dd") } })
    </div>
    <input type="submit" value="View" class="btn btn-default" />
}

<hr />
@if (ViewBag.OrderList != null)
{
    <table class="table">
        <tr>
            <th>No.</th>
            <th>Id</th>
            <th>Date</th>
            <th>Customer</th>
            <th>Employee</th>
            <th style="text-align:right">Amount</th>
            <th>Operator</th>
        </tr>
        @{
            int i = 0;
            double total = 0;
        }
        @foreach (Order order in ViewBag.OrderList)
        {
            total += order.Amount;
        <tr>
            <td>@(++i)</td>
            <td>@(order.Id.ToString("000000"))</td>
            <td>@(order.Date.ToString("MM-dd-yyyy"))</td>
            <td>@(order.Customer.AspNetUser.FirstName + " " + order.Customer.AspNetUser.LastName)</td>
            <td>@(order.Employee.AspNetUser.FirstName + " " + order.Employee.AspNetUser.LastName)</td>
            <td align="right">@(order.Amount.ToString("C2"))</td>
            <td>
                <a href="@Url.Action("Details",new { id = order.Id })">
                    <span class="glyphicon glyphicon-refresh" style="color:green"></span> Details
                </a>
            </td>
        </tr>            
        }
        <tr>
            <th colspan="5" style="text-align:right">Total:</th>
            <th style="text-align:right">@(total.ToString("C2"))</th>
        </tr>
    </table>
}
        <div>            
            @Html.ActionLink("Back to List", "Index")
        </div>